[project]
name = "alpha"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "yfinance",
    "uvicorn",
    "fastapi",
    "jinja2",
    "sqlalchemy>=2.0.51",
    "psycopg2-binary>=2.9.12",
    "python-multipart>=0.0.32",
]
